### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by guoshuaiS** [heshuting555/PADing#1]
你好，代码什么时候公开？

**Comment by heshuting555** [comment]
Thank you for your interest!&nbsp;
The code will be open source in two days！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: guoshuaiS ***@***.***&gt;
发送时间: 2023年6月12日 16:13
收件人: heshuting555/PADing ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [heshuting555/PADing] 问题 (Issue #1)





 
你好，代码什么时候公开？

**Comment by heshuting555** [comment]
Hi,

The code is uploaded!
